---
engines:
  fixme:
    enabled: true
  cppcheck:
    enabled: true
    exclude_paths:
      - third_party
    config:
      check: all
      inconclusive: false
      stds:
        - c++11
        - posix
ratings:
  paths: []
exclude_paths: []
