#ifndef LIBREDTIMER_GLOBAL_H
#define LIBREDTIMER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBREDTIMER_LIBRARY)
#  define LIBREDTIMERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBREDTIMERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBREDTIMER_GLOBAL_H
